[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
optimizer-runs = 10_000_000

[profile.production]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
eth-rpc-url = "https://eth-mainnet.g.alchemy.com/v2/API_KEY"
optimizer-runs = 10_000_000

[profile.ci]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
# ffi = true
optimizer-runs = 10_000_000

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "@forge-std/=lib/forge-std/src/",
    "@solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-v4.9.3/=lib/openzeppelin-contracts-v4.9.3/",
    "@openzeppelin-v5.0.0/=lib/openzeppelin-contracts-v5.0.0/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@maverick-v1-interfaces/=lib/maverick-v1-interfaces/contracts/interfaces/",
    "lib/forge-std:ds-test/=lib/forge-std/lib/ds-test/src/",
    "@crytic/=lib/crytic/contracts"
]

[rpc_endpoints]
goerli = "https://ethereum-goerli.publicnode.com"

[fmt]
line_length = 80
